/**
 * Vasim Hayat @ 2/10/2018
 */
export declare class FnWeatherConstatnt {
    static readonly WEATHER_ICONS: {
        Chance_of_Flurries: string;
        Chance_of_Rain: string;
        Chance_of_Freezing_Rain: string;
        Chance_of_Sleet: string;
        Chance_of_Snow: string;
        Chance_of_Thunderstorms: string;
        Chance_of_a_Thunderstorm: string;
        Clear: string;
        Cloudy: string;
        Flurries: string;
        Fog: string;
        Haze: string;
        Mostly_Cloudy: string;
        Mostly_Sunny: string;
        Partly_Cloudy: string;
        Partly_Sunny: string;
        Freezing_Rain: string;
        Rain: string;
        Sleet: string;
        Snow: string;
        Sunny: string;
        Thunderstorms: string;
        Thunderstorm: string;
        Overcast: string;
        Rain_Showers: string;
        Snow_Showers: string;
        Scattered_Clouds: string;
        'Light Rain': string;
        'Light Freezing Rain': string;
        'Light Snow': string;
        'Light Drizzle': string;
        Ice_Pellets: string;
    };
    static readonly WEATHER_STRINGS: {
        en: {
            Chance_of_Flurries: string;
            Chance_of_Rain: string;
            Chance_of_Freezing_Rain: string;
            Chance_of_Sleet: string;
            Chance_of_Snow: string;
            Chance_of_Thunderstorms: string;
            Chance_of_a_Thunderstorm: string;
            Clear: string;
            Cloudy: string;
            Flurries: string;
            Fog: string;
            Haze: string;
            Mostly_Cloudy: string;
            Mostly_Sunny: string;
            Partly_Cloudy: string;
            Partly_Sunny: string;
            Freezing_Rain: string;
            Rain: string;
            Sleet: string;
            Snow: string;
            Sunny: string;
            Thunderstorms: string;
            Thunderstorm: string;
            Overcast: string;
            Snow_Showers: string;
            'N/A': string;
            Scattered_Clouds: string;
            'Light Rain': string;
            'Light Freezing Rain': string;
            'Light Snow': string;
            'Light Drizzle': string;
            Ice_Pellets: string;
        };
        es: {
            Chance_of_Flurries: string;
            Chance_of_Rain: string;
            Chance_of_Freezing_Rain: string;
            Chance_of_Sleet: string;
            Chance_of_Snow: string;
            Chance_of_Thunderstorms: string;
            Chance_of_a_Thunderstorm: string;
            Clear: string;
            Cloudy: string;
            Flurries: string;
            Fog: string;
            Haze: string;
            Mostly_Cloudy: string;
            Mostly_Sunny: string;
            Partly_Cloudy: string;
            Partly_Sunny: string;
            Freezing_Rain: string;
            Rain: string;
            Sleet: string;
            Snow: string;
            Sunny: string;
            Thunderstorms: string;
            Thunderstorm: string;
            Overcast: string;
            Snow_Showers: string;
            'N/A': string;
            Scattered_Clouds: string;
            'Light Rain': string;
            'Light Freezing Rain': string;
            'Light Snow': string;
            'Light Drizzle': string;
            Ice_Pellets: string;
        };
        fr: {
            Chance_of_Flurries: string;
            Chance_of_Rain: string;
            Chance_of_Freezing_Rain: string;
            Chance_of_Sleet: string;
            Chance_of_Snow: string;
            Chance_of_Thunderstorms: string;
            Chance_of_a_Thunderstorm: string;
            Clear: string;
            Cloudy: string;
            Flurries: string;
            Fog: string;
            Haze: string;
            Mostly_Cloudy: string;
            Mostly_Sunny: string;
            Partly_Cloudy: string;
            Partly_Sunny: string;
            Freezing_Rain: string;
            Rain: string;
            Sleet: string;
            Snow: string;
            Sunny: string;
            Thunderstorms: string;
            Thunderstorm: string;
            Overcast: string;
            Snow_Showers: string;
            'N/A': string;
            Scattered_Clouds: string;
            'Light Rain': string;
            'Light Freezing Rain': string;
            'Light Snow': string;
            'Light Drizzle': string;
            Ice_Pellets: string;
        };
        zh: {
            Chance_of_Flurries: string;
            Chance_of_Rain: string;
            Chance_of_Freezing_Rain: string;
            Chance_of_Sleet: string;
            Chance_of_Snow: string;
            Chance_of_Thunderstorms: string;
            Chance_of_a_Thunderstorm: string;
            Clear: string;
            Cloudy: string;
            Flurries: string;
            Fog: string;
            Haze: string;
            Mostly_Cloudy: string;
            Mostly_Sunny: string;
            Partly_Cloudy: string;
            Partly_Sunny: string;
            Freezing_Rain: string;
            Rain: string;
            Sleet: string;
            Snow: string;
            Sunny: string;
            Thunderstorms: string;
            Thunderstorm: string;
            Overcast: string;
            Snow_Showers: string;
            'N/A': string;
            Scattered_Clouds: string;
            'Light Rain': string;
            'Light Freezing Rain': string;
            'Light Snow': string;
            'Light Drizzle': string;
            Ice_Pellets: string;
        };
        it: {
            Chance_of_Flurries: string;
            Chance_of_Rain: string;
            Chance_of_Freezing_Rain: string;
            Chance_of_Sleet: string;
            Chance_of_Snow: string;
            Chance_of_Thunderstorms: string;
            Chance_of_a_Thunderstorm: string;
            Clear: string;
            Cloudy: string;
            Flurries: string;
            Fog: string;
            Haze: string;
            Mostly_Cloudy: string;
            Mostly_Sunny: string;
            Partly_Cloudy: string;
            Partly_Sunny: string;
            Freezing_Rain: string;
            Rain: string;
            Sleet: string;
            Snow: string;
            Sunny: string;
            Thunderstorms: string;
            Thunderstorm: string;
            Overcast: string;
            Snow_Showers: string;
            'N/A': string;
            Scattered_Clouds: string;
            'Light Rain': string;
            'Light Freezing Rain': string;
            'Light Snow': string;
            'Light Drizzle': string;
            Ice_Pellets: string;
        };
        de: {
            Chance_of_Flurries: string;
            Chance_of_Rain: string;
            Chance_of_Freezing_Rain: string;
            Chance_of_Sleet: string;
            Chance_of_Snow: string;
            Chance_of_Thunderstorms: string;
            Chance_of_a_Thunderstorm: string;
            Clear: string;
            Cloudy: string;
            Flurries: string;
            Fog: string;
            Haze: string;
            Mostly_Cloudy: string;
            Mostly_Sunny: string;
            Partly_Cloudy: string;
            Partly_Sunny: string;
            Freezing_Rain: string;
            Rain: string;
            Sleet: string;
            Snow: string;
            Sunny: string;
            Thunderstorms: string;
            Thunderstorm: string;
            Overcast: string;
            Snow_Showers: string;
            'N/A': string;
            Scattered_Clouds: string;
            'Light Rain': string;
            'Light Freezing Rain': string;
            'Light Snow': string;
            'Light Drizzle': string;
            Ice_Pellets: string;
        };
    };
}
