/**
 * Created by mvasim on 12/9/17.
 */
import { FnDeviceConstant } from './fn-device.constant';
export declare class FNConstant {
    static readonly SPACE: string;
    static readonly SING_SPACE: string;
    static readonly EMPTYSTR: string;
    static readonly TILDE: string;
    static readonly FWD_SLASH: string;
    static readonly COMMA: string;
    static readonly HYPHEN: string;
    static readonly UNDERSCORE: string;
    static readonly DOT: string;
    static readonly PERC: string;
    static readonly NO: string;
    static readonly NULL_LC: string;
    static readonly UN_DEFINED: string;
    static readonly FALSE_LC: string;
    static readonly NULL: any;
    static readonly WEATHER_ICON_HASH: {
        Chance_of_Flurries: string;
        Chance_of_Rain: string;
        Chance_of_Freezing_Rain: string;
        Chance_of_Sleet: string;
        Chance_of_Snow: string;
        Chance_of_Thunderstorms: string;
        Chance_of_a_Thunderstorm: string;
        Clear: string;
        Cloudy: string;
        Flurries: string;
        Fog: string;
        Haze: string;
        Mostly_Cloudy: string;
        Mostly_Sunny: string;
        Partly_Cloudy: string;
        Partly_Sunny: string;
        Freezing_Rain: string;
        Rain: string;
        Sleet: string;
        Snow: string;
        Sunny: string;
        Thunderstorms: string;
        Thunderstorm: string;
        Overcast: string;
        Rain_Showers: string;
        Snow_Showers: string;
        Scattered_Clouds: string;
        'Light Rain': string;
        'Light Freezing Rain': string;
        'Light Snow': string;
        'Light Drizzle': string;
        Ice_Pellets: string;
    };
    static readonly WEATHER_STRINGS: {
        en: {
            Chance_of_Flurries: string;
            Chance_of_Rain: string;
            Chance_of_Freezing_Rain: string;
            Chance_of_Sleet: string;
            Chance_of_Snow: string;
            Chance_of_Thunderstorms: string;
            Chance_of_a_Thunderstorm: string;
            Clear: string;
            Cloudy: string;
            Flurries: string;
            Fog: string;
            Haze: string;
            Mostly_Cloudy: string;
            Mostly_Sunny: string;
            Partly_Cloudy: string;
            Partly_Sunny: string;
            Freezing_Rain: string;
            Rain: string;
            Sleet: string;
            Snow: string;
            Sunny: string;
            Thunderstorms: string;
            Thunderstorm: string;
            Overcast: string;
            Snow_Showers: string;
            'N/A': string;
            Scattered_Clouds: string;
            'Light Rain': string;
            'Light Freezing Rain': string;
            'Light Snow': string;
            'Light Drizzle': string;
            Ice_Pellets: string;
        };
        es: {
            Chance_of_Flurries: string;
            Chance_of_Rain: string;
            Chance_of_Freezing_Rain: string;
            Chance_of_Sleet: string;
            Chance_of_Snow: string;
            Chance_of_Thunderstorms: string;
            Chance_of_a_Thunderstorm: string;
            Clear: string;
            Cloudy: string;
            Flurries: string;
            Fog: string;
            Haze: string;
            Mostly_Cloudy: string;
            Mostly_Sunny: string;
            Partly_Cloudy: string;
            Partly_Sunny: string;
            Freezing_Rain: string;
            Rain: string;
            Sleet: string;
            Snow: string;
            Sunny: string;
            Thunderstorms: string;
            Thunderstorm: string;
            Overcast: string;
            Snow_Showers: string;
            'N/A': string;
            Scattered_Clouds: string;
            'Light Rain': string;
            'Light Freezing Rain': string;
            'Light Snow': string;
            'Light Drizzle': string;
            Ice_Pellets: string;
        };
        fr: {
            Chance_of_Flurries: string;
            Chance_of_Rain: string;
            Chance_of_Freezing_Rain: string;
            Chance_of_Sleet: string;
            Chance_of_Snow: string;
            Chance_of_Thunderstorms: string;
            Chance_of_a_Thunderstorm: string;
            Clear: string;
            Cloudy: string;
            Flurries: string;
            Fog: string;
            Haze: string;
            Mostly_Cloudy: string;
            Mostly_Sunny: string;
            Partly_Cloudy: string;
            Partly_Sunny: string;
            Freezing_Rain: string;
            Rain: string;
            Sleet: string;
            Snow: string;
            Sunny: string;
            Thunderstorms: string;
            Thunderstorm: string;
            Overcast: string;
            Snow_Showers: string;
            'N/A': string;
            Scattered_Clouds: string;
            'Light Rain': string;
            'Light Freezing Rain': string;
            'Light Snow': string;
            'Light Drizzle': string;
            Ice_Pellets: string;
        };
        zh: {
            Chance_of_Flurries: string;
            Chance_of_Rain: string;
            Chance_of_Freezing_Rain: string;
            Chance_of_Sleet: string;
            Chance_of_Snow: string;
            Chance_of_Thunderstorms: string;
            Chance_of_a_Thunderstorm: string;
            Clear: string;
            Cloudy: string;
            Flurries: string;
            Fog: string;
            Haze: string;
            Mostly_Cloudy: string;
            Mostly_Sunny: string;
            Partly_Cloudy: string;
            Partly_Sunny: string;
            Freezing_Rain: string;
            Rain: string;
            Sleet: string;
            Snow: string;
            Sunny: string;
            Thunderstorms: string;
            Thunderstorm: string;
            Overcast: string;
            Snow_Showers: string;
            'N/A': string;
            Scattered_Clouds: string;
            'Light Rain': string;
            'Light Freezing Rain': string;
            'Light Snow': string;
            'Light Drizzle': string;
            Ice_Pellets: string;
        };
        it: {
            Chance_of_Flurries: string;
            Chance_of_Rain: string;
            Chance_of_Freezing_Rain: string;
            Chance_of_Sleet: string;
            Chance_of_Snow: string;
            Chance_of_Thunderstorms: string;
            Chance_of_a_Thunderstorm: string;
            Clear: string;
            Cloudy: string;
            Flurries: string;
            Fog: string;
            Haze: string;
            Mostly_Cloudy: string;
            Mostly_Sunny: string;
            Partly_Cloudy: string;
            Partly_Sunny: string;
            Freezing_Rain: string;
            Rain: string;
            Sleet: string;
            Snow: string;
            Sunny: string;
            Thunderstorms: string;
            Thunderstorm: string;
            Overcast: string;
            Snow_Showers: string;
            'N/A': string;
            Scattered_Clouds: string;
            'Light Rain': string;
            'Light Freezing Rain': string;
            'Light Snow': string;
            'Light Drizzle': string;
            Ice_Pellets: string;
        };
        de: {
            Chance_of_Flurries: string;
            Chance_of_Rain: string;
            Chance_of_Freezing_Rain: string;
            Chance_of_Sleet: string;
            Chance_of_Snow: string;
            Chance_of_Thunderstorms: string;
            Chance_of_a_Thunderstorm: string;
            Clear: string;
            Cloudy: string;
            Flurries: string;
            Fog: string;
            Haze: string;
            Mostly_Cloudy: string;
            Mostly_Sunny: string;
            Partly_Cloudy: string;
            Partly_Sunny: string;
            Freezing_Rain: string;
            Rain: string;
            Sleet: string;
            Snow: string;
            Sunny: string;
            Thunderstorms: string;
            Thunderstorm: string;
            Overcast: string;
            Snow_Showers: string;
            'N/A': string;
            Scattered_Clouds: string;
            'Light Rain': string;
            'Light Freezing Rain': string;
            'Light Snow': string;
            'Light Drizzle': string;
            Ice_Pellets: string;
        };
    };
    static readonly FNDEVICE_ICONS_HASH: typeof FnDeviceConstant;
    static readonly FNDATE_FORMAT_MAP: {
        'MM/dd/YYYY': string;
        'MM/DD/YYYY': string;
        'DD/MM/YYYY': string;
        'dd/MM/YYYY': string;
        'dd/mm': string;
        'mm/dd': string;
        'dd/MM': string;
        'MM/dd': string;
        'MM/DD': string;
        'DD/MM': string;
        'MM/dd/yyyy': string;
        'MM/DD/yyyy': string;
        'mm/dd/yyyy': string;
        'DD/MM/yyyy': string;
        'dd/MM/yyyy': string;
        'yyyy/mm/dd': string;
        'yyyy/MM/dd': string;
    };
    static readonly FNTIME_FORMAT_MAP: {
        'HH:mm': string;
        'hh:mm:a': string;
        'hh:mm:ap': string;
    };
    static readonly NG_DATE_FORMAT_MAP: {
        'MM/dd/YYYY': string;
        'MM/DD/YYYY': string;
        'DD/MM/YYYY': string;
        'dd/MM/YYYY': string;
        'dd/mm': string;
        'mm/dd': string;
        'dd/MM': string;
        'MM/dd': string;
        'MM/DD': string;
        'DD/MM': string;
        'MM/dd/yyyy': string;
        'MM/DD/yyyy': string;
        'mm/dd/yyyy': string;
        'DD/MM/yyyy': string;
        'dd/MM/yyyy': string;
        'yyyy/mm/dd': string;
        'yyyy/MM/dd': string;
    };
    static readonly NG_TIME_FORMAT_MAP: {
        'HH:mm': string;
        'hh:mm a': string;
        'hh:mm:a': string;
        'hh:mm ap': string;
    };
}
export declare const FULL_NAME_REGX: RegExp;
export declare const NAME_REGEX: RegExp;
export declare const CURRENCY_REGEX: RegExp;
